iaas_settings:
  stemcell:
    name: (( merge ))
    version: (( merge ))
  subnet_configs:
    - name: docker-cache
      subnets: (( merge ))
  compilation_cloud_properties: (( merge ))
  resource_pool_cloud_properties:
    - name: docker-cache
      cloud_properties: (( merge ))
