iaas_settings:
  stemcell:
    name: (( merge ))
    version: (( merge ))
  subnet_configs:
    - name: docker-registry-0
      subnets: (( merge ))
    - name: docker-registry-1
      subnets: (( merge ))
    - name: docker-registry-2
      subnets: (( merge ))
    - name: docker-registry-3
      subnets: (( merge ))
  compilation_cloud_properties: (( merge ))
  resource_pool_cloud_properties:
    - name: docker-registry
      cloud_properties: (( merge ))
