iaas_settings:
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties:
    instance_type: m1.small
  resource_pool_cloud_properties:
    - name: docker-cache
      cloud_properties:
        instance_type: m1.medium
  subnet_configs:
    - name: docker-cache
      type: manual
      subnets:
      - range: 10.0.1.0/24
        gateway: 10.0.1.1
        static: []
        cloud_properties:
          net_id: DIEGO_1_NET_ID
          security_groups:
          - bosh
          - cf-private