#!/bin/bash

set -e -x -u

version=`cat docker-cache-version/number`

pushd diego-docker-cache-release
  bosh --parallel 4 -n create release --with-tarball --version $version --force

  mv dev_releases/diego-docker-cache/*.tgz ../created-docker-cache-release
popd
