#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

cf_deployment_name="cf-${ENVIRONMENT_NAME}"

./diego-docker-cache-release/scripts/ci/bosh_setup

pushd diego-docker-cache-release
  bosh -n create release
  bosh -n upload release --rebase || true

  spiff merge \
    manifest-generation/misc-templates/iaas-settings.yml \
    ${templates_path}/docker-registry/iaas-settings-internal.yml \
    ${stubs_path}/aws-resources.yml \
    > /tmp/iaas-settings.yml

  spiff merge \
    ${templates_path}/docker-registry/property-overrides-internal.yml \
    ${stubs_path}/aws-resources.yml \
    ${stubs_path}/cf/aws-keys.yml \
    > /tmp/property-overrides-internal.yml

  spiff merge \
    ${stubs_path}/docker-registry/property-overrides.yml \
    /tmp/property-overrides-internal.yml \
    > /tmp/property-overrides.yml

  bosh download manifest ${cf_deployment_name} > /tmp/cf.yml

  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    /tmp/property-overrides.yml \
    ${stubs_path}/docker-registry/instance-count-overrides.yml \
    ${stubs_path}/docker-registry/persistent-disk-overrides.yml \
    /tmp/iaas-settings.yml \
    ${stubs_path}/docker-registry/additional-jobs.yml \
    /tmp \
    > /tmp/docker-registry-deployment.yml

  bosh deployment /tmp/docker-registry-deployment.yml

  ./scripts/ci/emit-datadog-deploy-event started ${cf_deployment_name} docker-registry
  if bosh -n deploy; then
    ./scripts/ci/emit-datadog-deploy-event finished ${cf_deployment_name} docker-registry
  else
    ./scripts/ci/emit-datadog-deploy-event failed ${cf_deployment_name} docker-registry
    exit 1
  fi
popd
