#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

cf_deployment_name="cf-${ENVIRONMENT_NAME}"
tmpdir=$(mktemp -d /tmp/deploy-diego.XXXXX)

./docker-registry-release/scripts/ci/bosh_setup

bosh -n cleanup

bosh -n upload stemcell bosh-stemcell/*.tgz --skip-if-exists

pushd docker-registry-release
  bosh -n create release
  bosh -n upload release --rebase || true

  spiff merge \
    manifest-generation/misc-templates/iaas-settings.yml \
    ${templates_path}/docker-registry/iaas-settings-internal.yml \
    ${stubs_path}/aws-resources.yml \
    > ${tmpdir}/iaas-settings.yml
  bosh download manifest ${cf_deployment_name} > ${tmpdir}/cf.yml
  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/docker-registry/property-overrides.yml \
    ${stubs_path}/docker-registry/instance-count-overrides.yml \
    ${stubs_path}/docker-registry/persistent-disk-overrides.yml \
    ${tmpdir}/iaas-settings.yml \
    ${tmpdir} \
    > ${tmpdir}/docker-registry-deployment.yml
  bosh deployment ${tmpdir}/docker-registry-deployment.yml

  ./scripts/ci/emit-datadog-deploy-event started ${cf_deployment_name} docker-registry
  if bosh -n deploy; then
    ./scripts/ci/emit-datadog-deploy-event finished ${cf_deployment_name} docker-registry
  else
    ./scripts/ci/emit-datadog-deploy-event failed ${cf_deployment_name} docker-registry
    exit 1
  fi
popd
