#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"
version=`cat version/number`

cf_deployment_name="cf-${ENVIRONMENT_NAME}"

./docker-registry-release/scripts/ci/bosh_setup

bosh -n cleanup

pushd docker-registry-release
  bosh -n create release --with-tarball --version $version

  spiff merge \
    manifest-generation/misc-templates/iaas-settings.yml \
    ${templates_path}/docker-registry/iaas-settings-internal.yml \
    ${stubs_path}/aws-resources.yml \
    > ${tmpdir}/iaas-settings.yml

  bosh download manifest ${cf_deployment_name} > ${tmpdir}/cf.yml

  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/docker-registry/property-overrides.yml \
    ${stubs_path}/docker-registry/instance-count-overrides.yml \
    ${stubs_path}/docker-registry/persistent-disk-overrides.yml \
    ${tmpdir}/iaas-settings.yml \
    ${tmpdir} \
    > ${tmpdir}/docker-registry-deployment.yml
popd
