#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

cf_deployment_name="cf-${ENVIRONMENT_NAME}"

$(dirname $0)/bosh_setup

pushd diego-docker-cache-release
  spiff merge \
    manifest-generation/misc-templates/iaas-settings.yml \
    ${templates_path}/docker-registry/iaas-settings-internal.yml \
    ${stubs_path}/aws-resources.yml \
    > /tmp/iaas-settings.yml

  spiff merge \
    ${templates_path}/docker-registry/property-overrides-internal.yml \
    ${stubs_path}/aws-resources.yml \
    ${stubs_path}/cf/aws-keys.yml \
    > /tmp/property-overrides-internal.yml

  spiff merge \
    ${stubs_path}/docker-registry/property-overrides.yml \
    /tmp/property-overrides-internal.yml \
    > /tmp/property-overrides.yml

  bosh download manifest ${cf_deployment_name} > /tmp/cf.yml

  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    /tmp/property-overrides.yml \
    ${stubs_path}/docker-registry/instance-count-overrides.yml \
    ${stubs_path}/docker-registry/persistent-disk-overrides.yml \
    /tmp/iaas-settings.yml \
    ${stubs_path}/docker-registry/additional-jobs.yml \
    /tmp \
    > ../generated-manifest/diego-docker-cache-deployment.yml
popd
