#!/bin/bash

set -e -x -u

acceptance_tests_manifest=${PWD}/${DOCKER_REGISTRY_ACCEPTANCE_TESTS_MANIFEST}

$(dirname $0)/bosh_setup

# Report which releases were deployed together for this run of the DRATS
bosh deployments
bosh releases

bosh deployment ${acceptance_tests_manifest}

set +e
bosh run errand acceptance_tests --download-logs --keep-alive
errand_result=$?
set -e

original_name=$(ls acceptance_tests.0.*.tgz)
new_name=$(echo $original_name | sed 's/\.0\./\.0.0.0./')
mv $original_name docker_cache_$new_name
exit $errand_result
