---
name: docker-registry-release

director_uuid: <%= `bosh status --uuid` %>

releases:
  - name: docker-registry
    version: latest
  - name: cf
    version: latest


compilation:
  network: docker-registry
  workers: 1
  cloud_properties:
    name: docker-registry-subnet

jobs:
  - name: docker_registry
    instances: 1
    persistent_disk: 10240
    networks:
    - name: docker-registry
    resource_pool: docker-registry
    templates:
      - name: consul_agent
        release: cf
      - name: docker
        release: docker-registry
      - name: docker_registry
        release: docker-registry
    properties:
      consul:
        agent:
          services:
            - docker_registry
          servers:
            lan: [10.244.0.54] 

networks:
  - name: docker-registry
    # Assumes up to 5 VMs, including 1 static and 4 dynamic.
    subnets:
      - range: 10.244.2.0/30
        reserved: [10.244.2.1]
        static: [10.244.2.2]
        cloud_properties:
          name: docker-registry-subnet
      - range: 10.244.2.4/30
        reserved: [10.244.2.5]
        static: []
        cloud_properties:
          name: docker-registry-subnet
      - range: 10.244.2.8/30
        reserved: [10.244.2.9]
        static: []
        cloud_properties:
          name: docker-registry-subnet
      - range: 10.244.2.12/30
        reserved: [10.244.2.13]
        static: []
        cloud_properties:
          name: docker-registry-subnet
      - range: 10.244.2.16/30
        reserved: [10.244.2.17]
        static: []
        cloud_properties:
          name: docker-registry-subnet


resource_pools:
  - cloud_properties:
      name: docker-registry-subnet
    name: docker-registry
    network: docker-registry
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 5000-60000
  update_watch_time: 1000-60000
