name: docker-acceptance-tests

director_uuid: <%= `bosh status --uuid` %>

compilation:
  cloud_properties:
    name: random
  network: acceptance-tests
  reuse_compilation_vms: true
  workers: 6

jobs:
- instances: 1
  lifecycle: errand
  name: docker_acceptance_tests
  networks:
    - name: acceptance-tests
  resource_pool: acceptance-tests
  templates:
    - name: acceptance-tests
    - name: docker 
  release: docker-registry

networks:
- name: acceptance-tests
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.20.16/30
    reserved:
      - 10.244.20.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.20/30
    reserved:
      - 10.244.20.21
    static: []

properties:
  acceptance_tests:
    admin_password: admin
    admin_user: admin
    api: api.10.244.0.34.xip.io
    apps_domain: 10.244.0.34.xip.io
    secure_address: 10.244.16.2:4001
    consul_cluster: http://127.0.0.1:8500
    docker_executable: /var/vcap/packages/docker-1.6.0/docker
    docker_parameters: ['-H', 'tcp://0.0.0.0:4243']
    skip_ssl_validation: true
  docker_registry:
    address: 10.244.2.6:8080

releases:
- name: docker-registry
  version: latest

resource_pools:
- cloud_properties:
    name: random
  name: acceptance-tests
  network: acceptance-tests
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  max_in_flight: 10
  update_watch_time: 1000-60000

